// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: messages.proto
// Original file comments:
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0
//
#ifndef GRPC_messages_2eproto__INCLUDED
#define GRPC_messages_2eproto__INCLUDED

#include "messages.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace grpc_example {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "grpc_example.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc_example::GreetResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_example::GreetResponse>> AsyncGreet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_example::GreetResponse>>(AsyncGreetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_example::GreetResponse>> PrepareAsyncGreet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_example::GreetResponse>>(PrepareAsyncGreetRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_example::GreetResponse>* AsyncGreetRaw(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_example::GreetResponse>* PrepareAsyncGreetRaw(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc_example::GreetResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_example::GreetResponse>> AsyncGreet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_example::GreetResponse>>(AsyncGreetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_example::GreetResponse>> PrepareAsyncGreet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_example::GreetResponse>>(PrepareAsyncGreetRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response, std::function<void(::grpc::Status)>) override;
      void Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpc_example::GreetResponse>* AsyncGreetRaw(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_example::GreetResponse>* PrepareAsyncGreetRaw(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Greet_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Greet(::grpc::ServerContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Greet() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const ::grpc_example::GreetRequest* /*request*/, ::grpc_example::GreetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGreet(::grpc::ServerContext* context, ::grpc_example::GreetRequest* request, ::grpc::ServerAsyncResponseWriter< ::grpc_example::GreetResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Greet<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Greet() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc_example::GreetRequest, ::grpc_example::GreetResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response) { return this->Greet(context, request, response); }));}
    void SetMessageAllocatorFor_Greet(
        ::grpc::MessageAllocator< ::grpc_example::GreetRequest, ::grpc_example::GreetResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpc_example::GreetRequest, ::grpc_example::GreetResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const ::grpc_example::GreetRequest* /*request*/, ::grpc_example::GreetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Greet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc_example::GreetRequest* /*request*/, ::grpc_example::GreetResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Greet<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Greet() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const ::grpc_example::GreetRequest* /*request*/, ::grpc_example::GreetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Greet() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const ::grpc_example::GreetRequest* /*request*/, ::grpc_example::GreetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGreet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Greet() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Greet(context, request, response); }));
    }
    ~WithRawCallbackMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const ::grpc_example::GreetRequest* /*request*/, ::grpc_example::GreetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Greet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Greet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Greet() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpc_example::GreetRequest, ::grpc_example::GreetResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpc_example::GreetRequest, ::grpc_example::GreetResponse>* streamer) {
                       return this->StreamedGreet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Greet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Greet(::grpc::ServerContext* /*context*/, const ::grpc_example::GreetRequest* /*request*/, ::grpc_example::GreetResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGreet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc_example::GreetRequest,::grpc_example::GreetResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Greet<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Greet<Service > StreamedService;
};

}  // namespace grpc_example


#endif  // GRPC_messages_2eproto__INCLUDED
