// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: messages.proto

#include "messages.pb.h"
#include "messages.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace grpc_example {

static const char* Greeter_method_names[] = {
  "/grpc_example.Greeter/Greet",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel, options));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Greet_(Greeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc_example::GreetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpc_example::GreetRequest, ::grpc_example::GreetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Greet_, context, request, response);
}

void Greeter::Stub::async::Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpc_example::GreetRequest, ::grpc_example::GreetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Greet_, context, request, response, std::move(f));
}

void Greeter::Stub::async::Greet(::grpc::ClientContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Greet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpc_example::GreetResponse>* Greeter::Stub::PrepareAsyncGreetRaw(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpc_example::GreetResponse, ::grpc_example::GreetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Greet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpc_example::GreetResponse>* Greeter::Stub::AsyncGreetRaw(::grpc::ClientContext* context, const ::grpc_example::GreetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGreetRaw(context, request, cq);
  result->StartCall();
  return result;
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::grpc_example::GreetRequest, ::grpc_example::GreetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpc_example::GreetRequest* req,
             ::grpc_example::GreetResponse* resp) {
               return service->Greet(ctx, req, resp);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::Greet(::grpc::ServerContext* context, const ::grpc_example::GreetRequest* request, ::grpc_example::GreetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc_example

